Document: monitor
Title: Debian monitor Manual
Author: <insert document author here>
Abstract: This manual describes what monitor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/monitor/monitor.sgml.gz

Format: postscript
Files: /usr/share/doc/monitor/monitor.ps.gz

Format: text
Files: /usr/share/doc/monitor/monitor.text.gz

Format: HTML
Index: /usr/share/doc/monitor/html/index.html
Files: /usr/share/doc/monitor/html/*.html
